### ISSUE TITLE
Version > 1.0.1 occur error: [TypeError: (0 , _svgbaker2.default) is not a constructor]

### ISSUE THREAD

**Issue by l1shu** [anncwb/vite-plugin-svg-icons#16]
occur error when the version is 1.0.2

```
const svgSymbol = await new (0, _svgbaker2.default)().addSymbol({
                          ^

TypeError: (0 , _svgbaker2.default) is not a constructor
    at compilerIcon (/Users/samuelsli/Documents/MiniGame/gamemaker/packages/admin/node_modules/vite-plugin-svg-icons/dist/index.js:5304:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getSymbol (/Users/samuelsli/Documents/MiniGame/gamemaker/packages/admin/node_modules/vite-plugin-svg-icons/dist/index.js:5269:21)
    at async compilerIcons (/Users/samuelsli/Documents/MiniGame/gamemaker/packages/admin/node_modules/vite-plugin-svg-icons/dist/index.js:5281:9)
    at async createModuleCode (/Users/samuelsli/Documents/MiniGame/gamemaker/packages/admin/node_modules/vite-plugin-svg-icons/dist/index.js:5230:33)
    at async /Users/samuelsli/Documents/MiniGame/gamemaker/packages/admin/node_modules/vite-plugin-svg-icons/dist/index.js:5217:35
error Command failed with exit code 1.
```

the version 1.0.1 is NORMAL

**Comment by anncwb** [comment]
Upgrade to 1.0.4
